name: IG Poster

on:
  workflow_dispatch:   # 允許手動觸發
  schedule:
    # 每 15 分鐘執行一次（UTC 時間）
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run poster
        run: |
          python poster/main.py

      - name: Commit & push history updates (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add history
            git commit -m "chore(history): update posted records [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
